[package]
name = "rust_simple_service"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
hyper = "1.6.0"
serde = "1.0.219"
tokio = {version = "1.46.0", features = ["full"]}
tower = "0.5.2"
tracing = "0.1.41"
tracing-subscriber = {version = "0.3.19", features = ["env-filter"]}
